name: App Pipeline

on:
  # Trigger the workflow on push or pull request events on the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allow triggering this workflow manually from the Actions tab
  workflow_dispatch:

# Set up the job for this workflow
jobs:

  # Single job ('build-and-test') in this workflow
  # if multiple jobs, then they will run in parallel threads in separate runner environments
  build-and-test:

    # Use ubuntu-latest for the runner environment (virtual machine)
    runs-on: ubuntu-latest

    # Steps mostly contain CLI commands (via "run") and actions (via "uses")
    steps:
      # Check out the repo under $GITHUB_WORKSPACE so that job can access it
      - name: Check out the repo
      - uses: action/checkout@v2

      # Runs a single echo command using the runners shell
      - run: echo Entering Django CI/CD Pipleline!

      # Uses the action setup-python@v2 to install Python 3.9 to the runner environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Runs a set of commands to install dependencies in the runner environment
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Runs database migrations on the Django app
      - name: Run migrations
        run: python manage.py migrate

      # Run all tests with verbose flag
      - name: Run all tests
        run: pytest -v
